name: output
on: push

jobs:
  create-output:
    runs-on: ubuntu-latest
    outputs: # job level output
      test: ${{ steps.check-output.outputs.test }} # key: test, value: step level output
    steps:
      - name: echo output
        id: check-output
        run: echo "test=hello" >> "$GITHUB_OUTPUT" # step level output
      - name: check output
        run: |
          echo ${{ steps.check-output.outputs.test }}

  get-output:
    needs: [ create-output ]
    runs-on: ubuntu-latest
    steps:
      - name: get output
        run: | # needs.{job name}.outputs.{job output key}
          echo ${{ needs.create-output.outputs.test }}