name: cache
on:
  push:
    paths:
      - 'src/**' # src 파일 하위 모든 파일

jobs:
  cache:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: | # 캐싱할 경로
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }} # 캐시의 키, 해당 위치의 파일이 변경될 때마다 hash 값이 변경되므로 새로운 의존성이 추가되거나 변경되는 경우 새롭게 캐싱된다.
          restore-keys: | # 캐시 복구를 위한 키 
            ${{ runner.os }}-gradle-
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build
        shell: bash
