name: matrix
on: push

jobs:
  get-matrix:
    strategy:
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest ]
        version: [ 12, 14, 16 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: echo matrix value
        run: |
          echo ${{ matrix.os }} 
          echo ${{ matrix.version }} 
